### ISSUE TITLE
Learn How to Deploy WebApp changes to Inspect

### ISSUE THREAD

**Issue by LolandaE** [bcgov/invasivesBC-mussels-iOS#186]
**Describe the task**
Learn How to Deploy WebApp changes to Inspect

**Acceptance Criteria**
- [x] Understand how the Inspect padOS app interacts with Invasives WebApp to manage permissions
- [x] Identify the old Invasives repo
- [x] learn what is involved in deploying changes to the Web!App side of Inspect

**Additional context**
- There is an administrator role to grant permissions
- There should be another repo that has the WebApp (old and new - we want the old one)
- App might be using KeyCloak in a non-standard way
- We will need another ticket to cover deploying front end changes via Launchpad/App store
- Mike Wells/Andrea Williams will have an idea of how to deploy changes to WebApp
- Need to find the correct URL for this ---> https://invasivesbc.pathfinder.gov.bc.ca/admin
- Original/Old repo for web app (Has not been maintained for awhile)
https://github.com/bcgov/lucy-web
- Original repo references this one as being new version
https://github.com/bcgov/invasivesbc

**Comment by JulianForeman** [comment]
Realized I could have put this here earlier but our contact for this ticket is locked out of something and unable to get on teams this week.  Most likely he will be back on Monday and we can set up a meeting then.
