### ISSUE TITLE
Admin cannot change permissions for users

### ISSUE THREAD

**Issue by jakemorr** [bcgov/invasivesBC-mussels-iOS#188]
**Expected Behaviour**
When the Admin goes to the web app and they change a users permission it should be reflected in their access to the application
 
**Actual Behaviour**
When the admin goes to the web app they have access to the permissions change options but when a new permission is selected they receive an error.
 
**Implications**
The Service Owner is unable to provision access to new users, or remove access from previous ones.
 
** Steps To Reproduce**
Steps to reproduce the behaviour: This is where I need your help
1. Go to https://invasivesbc.apps.silver.devops.gov.bc.ca/admin and login with IDIR account

2. Homepage is shown below and the first step is to click “respond” for any of the new users requests that are pending  
![image.png](https://images.zenhubusercontent.com/5e333d0d274467ab166b46bc/2ef7a1eb-7b09-421d-a2c1-cad60f6625ee)

3. Click on “update access” in the below screen shot
![image.png](https://images.zenhubusercontent.com/5e333d0d274467ab166b46bc/3d3f78d6-3817-42b3-a694-a4d9d06afeae)

4. Error at the top of the screenshot appears after step 3 and then all the pending user requests disappear from the main homepage as shown in the screenshot below
![image.png](https://images.zenhubusercontent.com/5e333d0d274467ab166b46bc/38157a3f-24fb-419c-8026-4e2674088ff3)
 
Additional Context:
Possible memory leak causing a spike in memory crashing the app.  This is caused by the export all data function being called when trying to respond to a request.  Can either increase the minimum/maximum requested memory to cause spikes to not crash the service; or change the page so the export all data function isn't running unless called.

**Comment by LolandaE** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sustainment-Team-621fdc6b9ad7010018d8dc2c/issues/bcgov/invasivesBC-mussels-iOS/188?planning-poker) with ZenHub @Christopher-walsh22

**Comment by LolandaE** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sustainment-Team-621fdc6b9ad7010018d8dc2c/issues/bcgov/invasivesBC-mussels-iOS/188?planning-poker) with ZenHub @JulianForeman @norrisng-bc
