### ISSUE TITLE
Comments Field to Appear When Form is Ready  - INSPECT

### ISSUE THREAD

**Issue by LolandaE** [bcgov/invasivesBC-mussels-iOS#218]
**High Risk Inspection Form - Comments Field**

**As an** Invasive Fauna Unit Head, **I want** the comments field to only appear once the form is ready to be submitted, **so that** the Conservation Officers can’t add information that should be a part of the forms.

**Additional Context**
- What is the current character limit for the comments box and could we potentially limit that?
- ACTION: Consult UX practitioner (Jake/Lolanda)

**Acceptance Criteria**
- [ ] Given a user has not filled in mandatory sections, When they go to submit, Then the comments area is greyed out
- [ ] Given a user has filled in mandatory sections, When they go to submit, Then the comments area is available.

**Comment by jakemorr** [comment]
@davidclaveau Hi Dave this is the lowest priority for inspect leave this one for now.
