### ISSUE TITLE
6. Update API Tests to use new Keycloak Realm - Inspect/Lucy-Web

### ISSUE THREAD

**Issue by LolandaE** [bcgov/invasivesBC-mussels-iOS#242]
**Describe the task**
Update API Tests to use Keycloak Gold

**Purpose**
The reason why this task is needed and/or what value it adds.

**Acceptance Criteria**
- [ ] Point API Test logins to Keycloak Gold

**Additional context**
N/A

**Comment by davidclaveau** [comment]
No issues with API tests when deploying to dev. There _shouldn't_ be an issue with deploying to prod.
