### ISSUE TITLE
Apple App Store Certificate Renewal

### ISSUE THREAD

**Issue by Christopher-walsh22** [bcgov/invasivesBC-mussels-iOS#250]
On October 10th the public Apple App Store distribution certificate will expire. In order to update our app we will need to refresh this certificate. I have seen some basic information about this on the devops-mobile-development channel in Rocket Chat (https://chat.developer.gov.bc.ca/channel/devops-mobile-development).

Last year Karl Hardin reached out to the team with information on how we could complete this process. A keychain password was supplied by Karl which was required for renewal.

**Comment by davidclaveau** [comment]
Should be steps to re-issuing certs here: https://mvp.developer.gov.bc.ca/docs/default/component/mobile-developer-guide
