### ISSUE TITLE
Update INSPECT/LUCY to use Keycloak for managing roles and permissions

### ISSUE THREAD

**Issue by davidclaveau** [bcgov/invasivesBC-mussels-iOS#281]
**Describe the task**
Migrate the permission logic to use Keycloak instead of the INSPECT/LUCY app's internal database user-management setup.

**Purpose**
Currently, changing user roles requires running a script on the LUCY database, or manually updating roles by porting the database. By updating the app to use Keycloak roles, we can align the app's permission setup with other government apps and use the SSO UI to add/remove users and roles with greater ease.

**Acceptance Criteria**
- [x] Only users with valid roles can access the INSPECT app
- [x] Invalid users are met with the "Access Requested" screen when they do not have the correct permissions
- [x] Only users with valid roles can submit inspections to the LUCY db
- [x] Invalid users receive errors when attempting to submit inspections without the correct permissions ("user role is not authorized to access this route")

**Additional context**
- To ensure there's no issue with permissions and roles, the LUCY database's `user_role` table's `role_code_id` might need to be updated to mirror Keycloak permissions. E.g. "Admin" in Keycloak updates `role_code_id` to 1 in the database, etc.

**Comment by LocalNewsTV** [comment]
Authentication files were cleaned up, user roles are now determined by keycloak.
