### ISSUE TITLE
Onboard new Dev to Inspect and Lucy-Web

### ISSUE THREAD

**Issue by jakemorr** [bcgov/invasivesBC-mussels-iOS#314]
**Describe the task**
Onboard a new dev on to Inspect and Lucy-Web, ensure they are familiar with Swift/Xcode, and the work already done to migrate to Swift-UI

**Purpose**
the Dev most knowledgable on Inspect is scheduled to graduate from sustainment, and a new dev is starting, the hope is to pass key knowledge and skills to the new dev as necessary.

**Acceptance Criteria**
- [x] Workflow of adding stuff (Complicated)
- [x] Onboard to Swift UI Re-write
- [x] Introduce new dev to Service Owner and Advise on best practices to support application

**For new Dev**
- [x] New Dev makes arbitrary end-to-end feature in the existing iOS application on their own device to better understand the workflow of the application
    - [x] Two buttons added to form
    - [x] Second button conditionally Renders
    - [x] API Receives Form Data
    - [x] New values displayed in local database

**Additional context**
Do not merge or push any part of the arbitrary feature to to GitHub

**Comment by LocalNewsTV** [comment]
Dumped more acceptance criteria into ticket for New Dev to contribute to.
