### ISSUE TITLE
Deploy to TestFlight

### ISSUE THREAD

**Issue by Keegnan** [bcgov/invasivesBC-mussels-iOS#321]
**Describe the task**
Able to deploy the app to TestFlight.

**Purpose**
To get it into TestFlight and have the SO view the changes in TestFlight.

**Acceptance Criteria**
- [x] Create a new version of app to deploy
- [x] The version ready to go will be the text change
- [ ] Get the change reviewed by the SO

**Additional context**
- dependent on ticket #320

**Comment by PaulGarewal** [comment]
# Progress Update

## New Certificate is Required to Proceed with deployment 

- error: Provisioning profile "InvasivesBC Muscles - 2023/24" expired on Sep 19, 2024. (in target 'ipad' from project 'ipad')
